// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrsu42n-gQsLFdY-hvMoPM3nw0VmZbI7I',
    appId: '1:577440738276:web:be1306ca3f01e15b0275f1',
    messagingSenderId: '577440738276',
    projectId: 'smart-pocket-fdccf',
    authDomain: 'smart-pocket-fdccf.firebaseapp.com',
    storageBucket: 'smart-pocket-fdccf.firebasestorage.app',
    measurementId: 'G-KG8MT75VBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChcgWXqqxsr-fRl-SihXft9UXJssDTcB8',
    appId: '1:577440738276:android:0d10322244ccd2b60275f1',
    messagingSenderId: '577440738276',
    projectId: 'smart-pocket-fdccf',
    storageBucket: 'smart-pocket-fdccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ31UZhKB2l2JAYhPIdt9VtaZUn_Fp5WI',
    appId: '1:577440738276:ios:c9e09ea7360f68ae0275f1',
    messagingSenderId: '577440738276',
    projectId: 'smart-pocket-fdccf',
    storageBucket: 'smart-pocket-fdccf.firebasestorage.app',
    iosBundleId: 'com.example.smartPocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ31UZhKB2l2JAYhPIdt9VtaZUn_Fp5WI',
    appId: '1:577440738276:ios:c9e09ea7360f68ae0275f1',
    messagingSenderId: '577440738276',
    projectId: 'smart-pocket-fdccf',
    storageBucket: 'smart-pocket-fdccf.firebasestorage.app',
    iosBundleId: 'com.example.smartPocket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrsu42n-gQsLFdY-hvMoPM3nw0VmZbI7I',
    appId: '1:577440738276:web:79eb450e27eb420c0275f1',
    messagingSenderId: '577440738276',
    projectId: 'smart-pocket-fdccf',
    authDomain: 'smart-pocket-fdccf.firebaseapp.com',
    storageBucket: 'smart-pocket-fdccf.firebasestorage.app',
    measurementId: 'G-8HF1ZGG8JH',
  );
}
